# Generated by Django 5.0.2 on 2024-03-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_attendancemarkings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemarkings',
            name='subject',
        ),
    ]
